glyphs:
  gcp:
    - type: dnsManagedZone
      dnsec: on #default on options off import
      name: int-cp-ligocloud-tech #defau para url cambia - por .
      visbility: public #default public option internal
      description: a nice long string
    - type: dnsRecordSet
      url: www.epe.com
      name: pepe-com
      dnsType: cname # default A 
      ttl: 8321 # defaults 30 segs
      managedZone: pepe.com
      records:
        - pepe.com
      #or
      compueAddresses:
        - name: la-ip
          namespace: optional