apiVersion: v2
name: kaster
version: 1.0
description: a kaster for the glyphs system.
home: https://github.com/kast-spells
sources:
  - https://github.com/kast-spells/kast-release
maintainers:
  - name: namen malkav
    email: namenmalkav@gmail.com
  - name: laaledesiempre
    email: laaledesiempre@disroot.org