{{/*kast - Kubernetes arcane spelling technology
Copyright (C) 2023 namenmalkv@gmail.com
Licensed under the GNU GPL v3. See LICENSE file for details.
*/}}
{{- define "gcp.keyRing" }}
{{- $root := index . 0 -}}
{{- $glyphDefinition := index . 1}}
---
apiVersion: kms.cnrm.cloud.google.com/v1beta1
kind: KMSKeyRing
metadata:
  name: {{ $glyphDefinition.name  }}
  annotations:
    {{- include "common.infra.annotations" $root | nindent 4}}
  labels:
    {{- include "common.infra.labels" $root | nindent 4 }}
spec:
  location:  {{ default "global" $glyphDefinition.location }}
{{- end }}
