{{/*kast - Kubernetes arcane spelling technology
Copyright (C) 2023 namenmalkv@gmail.com
Licensed under the GNU GPL v3. See LICENSE file for details.
*/}}
{{- define "vault.randomSecret" -}}
{{- $root := index . 0 -}}
{{- $secretName := index . 1 }}
{{- $secret := index . 2 }}
{{- $vaultServer := get (include "runicIndexer.runicIndexer" (list $root.Values.lexicon (dict "selector" (dict "secret-manager" "vault")) "secret-manager" $root.Values.chapter.name ) | fromJson) "results" }}
{{- range $vaultConf := $vaultServer }}
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: {{ $secretName }}
spec:
  {{- include "vault.connect" (list $root $vaultConf "") | nindent 2 }}
  isKVSecretsEngineV2: true
  path: {{ include "generateSecretPath" ( list $root $secretName $secret ) }}
  secretKey: {{ default "password" $secret.key }}
  secretFormat:
    passwordPolicyName: {{ default "simple-password-policy" ($secret).passPolicyName }}
  {{- end }}
{{- end }}